showErrorDetails = "none"

[client]
showErrorDetails = "none"

[theme]
primaryColor = "3C8F50"
backgroundColor = "black"
secondaryBackgroundColor = "2E2E2E"
textColor = "white"

[secrets]
files = [ "~/.streamlit/secrets.toml", "~/project directory/.streamlit/secrets.toml"]